### ISSUE TITLE
TLS ciphers broken

### ISSUE THREAD

**Issue by jpawlowski** [iobroker-community-adapters/ioBroker.email#17]
It seems that supported TLS ciphers are incomplete/outdated. After STARTTLS, the connector is unable to find a common cipher suite:

````shell
Error 140486513518400:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:802:
````

I am using https://github.com/buanet/docker-iobroker Docker image, not sure if this is related to outdated Node environment (as I am not a Node expert).

This is what the mailserver actually offers:

```shell
# for v in ssl2 ssl3 tls1 tls1_1 tls1_2; do
#  for c in $(openssl ciphers 'ALL:eNULL' | tr ':' ' '); do
#  openssl s_client -connect 1.2.3.4:25 -starttls smtp \
#  -cipher $c -$v <<< "Q" > /dev/null 2>&1 && echo -e "$v:\t$c"
#  done
# done

tls1:	ECDHE-ECDSA-AES256-SHA
tls1:	ECDHE-ECDSA-AES128-SHA
tls1:	ECDHE-ECDSA-DES-CBC3-SHA
tls1_1:	ECDHE-ECDSA-AES256-SHA
tls1_1:	ECDHE-ECDSA-AES128-SHA
tls1_1:	ECDHE-ECDSA-DES-CBC3-SHA
tls1_2:	ECDHE-ECDSA-AES256-GCM-SHA384
tls1_2:	ECDHE-ECDSA-AES256-SHA384
tls1_2:	ECDHE-ECDSA-AES256-SHA
tls1_2:	ECDHE-ECDSA-AES128-GCM-SHA256
tls1_2:	ECDHE-ECDSA-AES128-SHA256
tls1_2:	ECDHE-ECDSA-AES128-SHA
tls1_2:	ECDHE-ECDSA-DES-CBC3-SHA
```

Any other cipher suites are disabled for security reasons (which is quite common I believe).

**Comment by Apollon77** [comment]
Could it be that the mail server only supports old ciphers bit nodejs is 10.16+ and this is the reason for some ciphers nonlinear allowed? (Was a change in OpenSSL in nodejs itself)

**Comment by jpawlowski** [comment]
The Postfix server is running on OPNsense which is more or less "bleeding edge" when it's about being up-to-date. The ciphers that this Postfix instance supports is what I have added to the end of my post above. It seems there is no match for any of those on the Node.js side.

André's Docker image is still on Node.js 8.x (v 10.x seems to be in beta - however, new LTS version is already 12.x so he might be just a little behind... ;-)).

However, are you saying upgrading Node.js might help?

**Comment by Apollon77** [comment]
Nodejs 10.16+ uses OpenSSL 1.1 instead of 1.0 ... so maybe this helps. So switching to nodejs 10 might be an idea

**Comment by jpawlowski** [comment]
It seems that before I can do that, we need to overcome another issue popping up:

`````
2019-10-26 16:20:54.792 - info: host.demucvmcp01iob instance system.adapter.email.0 started with pid 1668
--
2019-10-26 16:20:55.656 - info: email.0 (1668) starting. Version 1.0.5 in /opt/iobroker/node_modules/iobroker.email, node: v10.17.0
2019-10-26 16:21:03.718 - info: email.0 (1668) Send email: {"subject":"ioBroker","to":"abcdef@googlemail.com","from":"test ","text":"This is test email!"}
2019-10-26 16:21:08.793 - error: email.0 (1668) uncaught exception: Converting circular structure to JSON
2019-10-26 16:21:08.793 - error: email.0 (1668) TypeError: Converting circular structure to JSON
at JSON.stringify ()
at transport.sendMail (/opt/iobroker/node_modules/iobroker.email/email.js:198:47)
at transporter.send.args (/opt/iobroker/node_modules/nodemailer/lib/mailer/index.js:226:21)
at SMTPConnection.connection.once.err (/opt/iobroker/node_modules/nodemailer/lib/smtp-transport/index.js:175:24)
at Object.onceWrapper (events.js:286:20)
at SMTPConnection.emit (events.js:198:13)
at SMTPConnection._onError (/opt/iobroker/node_modules/nodemailer/lib/smtp-connection/index.js:761:14)
at TLSSocket.SMTPConnection._onSocketError.error (/opt/iobroker/node_modules/nodemailer/lib/smtp-connection/index.js:190:45)
at TLSSocket.emit (events.js:198:13)
at emitErrorNT (internal/streams/destroy.js:91:8)
2019-10-26 16:21:09.297 - info: email.0 (1668) terminating
2019-10-26 16:21:09.298 - info: email.0 (1668) Terminated (NO_ERROR): Without reason
2019-10-26 16:21:09.806 - error: host.demucvmcp01iob Caught by controller[0]: TypeError: Converting circular structure to JSON
2019-10-26 16:21:09.807 - error: host.demucvmcp01iob Caught by controller[0]: at JSON.stringify ()
2019-10-26 16:21:09.807 - error: host.demucvmcp01iob Caught by controller[0]: at transport.sendMail (/opt/iobroker/node_modules/iobroker.email/email.js:198:47)
2019-10-26 16:21:09.807 - error: host.demucvmcp01iob Caught by controller[0]: at transporter.send.args (/opt/iobroker/node_modules/nodemailer/lib/mailer/index.js:226:21)
2019-10-26 16:21:09.807 - error: host.demucvmcp01iob Caught by controller[0]: at SMTPConnection.connection.once.err (/opt/iobroker/node_modules/nodemailer/lib/smtp-transport/index.js:175:24)
2019-10-26 16:21:09.807 - error: host.demucvmcp01iob Caught by controller[0]: at Object.onceWrapper (events.js:286:20)
2019-10-26 16:21:09.807 - error: host.demucvmcp01iob Caught by controller[0]: at SMTPConnection.emit (events.js:198:13)
2019-10-26 16:21:09.807 - error: host.demucvmcp01iob Caught by controller[0]: at SMTPConnection._onError (/opt/iobroker/node_modules/nodemailer/lib/smtp-connection/index.js:761:14)
2019-10-26 16:21:09.807 - error: host.demucvmcp01iob Caught by controller[0]: at TLSSocket.SMTPConnection._onSocketError.error (/opt/iobroker/node_modules/nodemailer/lib/smtp-connection/index.js:190:45)
2019-10-26 16:21:09.807 - error: host.demucvmcp01iob Caught by controller[0]: at TLSSocket.emit (events.js:198:13)
2019-10-26 16:21:09.807 - error: host.demucvmcp01iob Caught by controller[0]: at emitErrorNT (internal/streams/destroy.js:91:8)
2019-10-26 16:21:09.807 - info: host.demucvmcp01iob instance system.adapter.email.0 terminated with code 0 (NO_ERROR)
2019-10-26 16:21:09.808 - info: host.demucvmcp01iob Restart adapter system.adapter.email.0 because enabled


``````

**Comment by buanet** [comment]
I released v4 of my Docker image yesterday. Should be available under "latest" now. This version includes node10.

Regards,
André

**Comment by Apollon77** [comment]
Seems that there is a logging and the object structure is bad now. We can remove the logging ...

**Comment by Apollon77** [comment]
The error happens when he troes to log an error object. please try GitHub version of Adapter, I chnged loggign there a bit

**Comment by jpawlowski** [comment]
Not much output to offer after that:

`````
undefined2019-10-27 09:32:12.871 - silly: email.0 (2252) States redis pmessage io.messagebox.system.adapter.email.0/io.messagebox.system.adapter.email.0:{"command":"send","message":{"subject":"ioBroker","to":"abcdef@googlemail.com","from":"test ","text":"This is test email!","options":{"host":"192.168.6.1","port":"25","secure":false,"auth":{"user":"","pass":""},"service":""}},"from":"system.adapter.admin.0","callback":{"message":{"subject":"ioBroker","to":"abcdef@googlemail.com","from":"test ","text":"This is test email!","options":{"host":"192.168.6.1","port":"25","secure":false,"auth":{"user":"","pass":""},"service":""}},"id":74,"ack":false,"time":1572165132870},"_id":68981075}
--
2019-10-27 09:32:12.916 - info: email.0 (2252) Send email: {"subject":"ioBroker","to":"abcdef@googlemail.com","from":"test ","text":"This is test email!"}
2019-10-27 09:32:13.134 - error: email.0 (2252) Error undefined
`````
